services:
 postgres:
   image: postgres
   environment:  # Corrigido o typo em "environment"
     - POSTGRES_PASSWORD=123456
      PGDATA: /data/postgres
   ports:
     - 5432:5432
   volumes:
     - postgres:/data/postgres
     
   restart: unless-stopped

volumes:
  pgdata:
