import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./nav/Navbar";



export const metadata: Metadata = {
  title: "app leilao",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
